package com.hz.admin.db.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hz_custno_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TCustnoInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_custno_info.custno
     *
     * @mbg.generated
     */
    private Long custno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_custno_info.nick
     *
     * @mbg.generated
     */
    private String nick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_custno_info.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_custno_info.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_custno_info.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_custno_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_custno_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hz_custno_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_custno_info.custno
     *
     * @return the value of hz_custno_info.custno
     *
     * @mbg.generated
     */
    public Long getCustno() {
        return custno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_custno_info.custno
     *
     * @param custno the value for hz_custno_info.custno
     *
     * @mbg.generated
     */
    public void setCustno(Long custno) {
        this.custno = custno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_custno_info.nick
     *
     * @return the value of hz_custno_info.nick
     *
     * @mbg.generated
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_custno_info.nick
     *
     * @param nick the value for hz_custno_info.nick
     *
     * @mbg.generated
     */
    public void setNick(String nick) {
        this.nick = nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_custno_info.address
     *
     * @return the value of hz_custno_info.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_custno_info.address
     *
     * @param address the value for hz_custno_info.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_custno_info.phone
     *
     * @return the value of hz_custno_info.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_custno_info.phone
     *
     * @param phone the value for hz_custno_info.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_custno_info.status
     *
     * @return the value of hz_custno_info.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_custno_info.status
     *
     * @param status the value for hz_custno_info.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_custno_info.update_time
     *
     * @return the value of hz_custno_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_custno_info.update_time
     *
     * @param updateTime the value for hz_custno_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_custno_info.create_time
     *
     * @return the value of hz_custno_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_custno_info.create_time
     *
     * @param createTime the value for hz_custno_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}