package com.hz.admin.db.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hz_custno_role
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TCustnoRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_custno_role.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_custno_role.custno
     *
     * @mbg.generated
     */
    private String custno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_custno_role.role_id
     *
     * @mbg.generated
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_custno_role.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_custno_role.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hz_custno_role
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_custno_role.id
     *
     * @return the value of hz_custno_role.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_custno_role.id
     *
     * @param id the value for hz_custno_role.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_custno_role.custno
     *
     * @return the value of hz_custno_role.custno
     *
     * @mbg.generated
     */
    public String getCustno() {
        return custno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_custno_role.custno
     *
     * @param custno the value for hz_custno_role.custno
     *
     * @mbg.generated
     */
    public void setCustno(String custno) {
        this.custno = custno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_custno_role.role_id
     *
     * @return the value of hz_custno_role.role_id
     *
     * @mbg.generated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_custno_role.role_id
     *
     * @param roleId the value for hz_custno_role.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_custno_role.update_time
     *
     * @return the value of hz_custno_role.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_custno_role.update_time
     *
     * @param updateTime the value for hz_custno_role.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hz_custno_role.create_time
     *
     * @return the value of hz_custno_role.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hz_custno_role.create_time
     *
     * @param createTime the value for hz_custno_role.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}