package com.hz.admin.pojo.bo.menu;

import com.dzzh.hz.hzsf.common.pojo.CommonPojo;

/**
 * @Classname MenuQueryBO
 * @Description TODO
 * @Date 2020-08-25 22:28
 * @Created by hzong
 */
public class MenuQueryBO extends CommonPojo {

    /**
     * Database Column Remarks:
     *   菜单名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.menu_name
     *
     * @mbg.generated
     */
    private String menuName;
    /**
     * Database Column Remarks:
     *
     *级别
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.is_enable
     *
     * @mbg.generated
     */
    private Integer level;

    public String getMenuName() {
        return menuName;
    }

    public MenuQueryBO setMenuName(String menuName) {
        this.menuName = menuName;
        return this;
    }

    public Integer getLevel() {
        return level;
    }

    public MenuQueryBO setLevel(Integer level) {
        this.level = level;
        return this;
    }


}
