package com.hz.admin.db.entity.ex;

/**
 * @Classname CustNoRoleDO
 * @Description TODO
 * @Date 2020-01-31 15:51
 * @Created by hzong
 */
public class SysRoleMenuDO {
    /**
     * Database Column Remarks:
     *   主键字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.menu_id
     *
     * @mbg.generated
     */
    private Long menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.menu_no
     *
     * @mbg.generated
     */
    private String menuNo;

    /**
     * Database Column Remarks:
     *   菜单名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.menu_name
     *
     * @mbg.generated
     */
    private String menuName;

    /**
     * Database Column Remarks:
     *   父菜单
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.menu_parent_no
     *
     * @mbg.generated
     */
    private String menuParentNo;

    /**
     * Database Column Remarks:
     *   菜单序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.seq
     *
     * @mbg.generated
     */
    private Integer seq;

    /**
     * Database Column Remarks:
     *   从 1开始
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.level
     *
     * @mbg.generated
     */
    private Integer level;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.description
     *
     * @mbg.generated
     */
    private String description;


    public Long getMenuId() {
        return menuId;
    }

    public SysRoleMenuDO setMenuId(Long menuId) {
        this.menuId = menuId;
        return this;
    }

    public String getMenuNo() {
        return menuNo;
    }

    public SysRoleMenuDO setMenuNo(String menuNo) {
        this.menuNo = menuNo;
        return this;
    }

    public String getMenuName() {
        return menuName;
    }

    public SysRoleMenuDO setMenuName(String menuName) {
        this.menuName = menuName;
        return this;
    }

    public String getMenuParentNo() {
        return menuParentNo;
    }

    public SysRoleMenuDO setMenuParentNo(String menuParentNo) {
        this.menuParentNo = menuParentNo;
        return this;
    }

    public Integer getSeq() {
        return seq;
    }

    public SysRoleMenuDO setSeq(Integer seq) {
        this.seq = seq;
        return this;
    }

    public String getUrl() {
        return url;
    }

    public Integer getLevel() {
        return level;
    }

    public SysRoleMenuDO setLevel(Integer level) {
        this.level = level;
        return this;
    }

    public SysRoleMenuDO setUrl(String url) {
        this.url = url;
        return this;
    }

    public String getDescription() {
        return description;
    }

    public SysRoleMenuDO setDescription(String description) {
        this.description = description;
        return this;
    }
}
