package com.hz.admin.model.pojo.dto.menu;

import com.hz.hzsf.common.pojo.RequestPage;

/**
 * @Classname MenuRequestQueryPageDTO
 * @Description TODO
 * @Date 2019-08-31 19:57
 * @Created by hzong
 */
public class MenuRequestQueryPageDTO extends RequestPage {
    /**
     * Database Column Remarks:
     *   主键字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.menu_id
     *
     * @mbg.generated
     */

    private Long menuId;

    /**
     * Database Column Remarks:
     *   菜单名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.menu_name
     *
     * @mbg.generated
     */
    private String menuName;

    /**
     * Database Column Remarks:
     *   父菜单
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.menu_parent
     *
     * @mbg.generated
     */
    private Long menuParent;

    /**
     * Database Column Remarks:
     *   菜单序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.seq
     *
     * @mbg.generated
     */
    private Integer seq;

    /**
     * Database Column Remarks:
     *   是否启用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.is_enable
     *
     * @mbg.generated
     */
    private Integer Status;

    public Integer getStatus() {
        return Status;
    }

    public MenuRequestQueryPageDTO setStatus(Integer status) {
        Status = status;
        return this;
    }

    public Long getMenuId() {
        return menuId;
    }

    public MenuRequestQueryPageDTO setMenuId(Long menuId) {
        this.menuId = menuId;
        return this;
    }

    public String getMenuName() {
        return menuName;
    }

    public MenuRequestQueryPageDTO setMenuName(String menuName) {
        this.menuName = menuName;
        return this;
    }

    public Long getMenuParent() {
        return menuParent;
    }

    public MenuRequestQueryPageDTO setMenuParent(Long menuParent) {
        this.menuParent = menuParent;
        return this;
    }

    public Integer getSeq() {
        return seq;
    }

    public MenuRequestQueryPageDTO setSeq(Integer seq) {
        this.seq = seq;
        return this;
    }

}
