package com.hz.admin.model.pojo.dto.menu;

import com.hz.hzsf.common.pojo.RequestPage;

import javax.validation.constraints.NotNull;

/**
 * @Classname MenuRequestQueryPageDTO
 * @Description TODO
 * @Date 2019-08-31 19:57
 * @Created by hzong
 */
public class MenuRequestQueryPageDTO extends RequestPage {


    /**
     * Database Column Remarks:
     *   菜单名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.menu_name
     *
     * @mbg.generated
     */
    @NotNull
    private String menuName;
    /**
     * Database Column Remarks:
     *   是否启用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.is_enable
     *
     * @mbg.generated
     */
    private Integer status;

    public String getMenuName() {
        return menuName;
    }

    public MenuRequestQueryPageDTO setMenuName(String menuName) {
        this.menuName = menuName;
        return this;
    }

    public Integer getStatus() {
        return status;
    }

    public MenuRequestQueryPageDTO setStatus(Integer status) {
        this.status = status;
        return this;
    }
}
