package com.hz.admin.model.pojo.dto.menu;

import com.dzzh.hz.hzsf.common.pojo.RequestPage;
import com.dzzh.hz.hzsf.common.pojo.dto.common.RequestPageDTO;

import javax.validation.constraints.NotNull;

/**
 * @Classname MenuRequestQueryPageDTO
 * @Description TODO
 * @Date 2019-08-31 19:57
 * @Created by hzong
 */
public class MenuRequestQueryPageDTO extends RequestPageDTO {


    /**
     * Database Column Remarks:
     *   菜单名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.menu_name
     *
     * @mbg.generated
     */
    @NotNull
    private String menuName;
    /**
     * Database Column Remarks:
     *
     *级别
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.is_enable
     *
     * @mbg.generated
     */
    private Integer level;

    public String getMenuName() {
        return menuName;
    }

    public MenuRequestQueryPageDTO setMenuName(String menuName) {
        this.menuName = menuName;
        return this;
    }

    public Integer getLevel() {
        return level;
    }

    public MenuRequestQueryPageDTO setLevel(Integer level) {
        this.level = level;
        return this;
    }
}
