package com.hz.admin.model.pojo.dto.menu;

import com.dzzh.hz.hzsf.common.pojo.CommonPojo;

import java.util.Date;

/**
 * @Classname SysMenuItemDTO
 * @Description TODO
 * @Date 2020-09-01 20:17
 * @Created by hzong
 */
public class SysMenuItemDTO extends CommonPojo {
    /**
     * 菜单编码
     */
    private String menuNo;
    /**
     * 菜单名称
     */
    private String menuName;
    /**
     * 菜单描述
     */
    private String description;
    /**
     * 状态
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    public Date getUpdateTime() {
        return updateTime;
    }

    public SysMenuItemDTO setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public SysMenuItemDTO setCreateTime(Date createTime) {
        this.createTime = createTime;
        return this;
    }

    public String getMenuNo() {
        return menuNo;
    }

    public SysMenuItemDTO setMenuNo(String menuNo) {
        this.menuNo = menuNo;
        return this;
    }

    public String getMenuName() {
        return menuName;
    }

    public SysMenuItemDTO setMenuName(String menuName) {
        this.menuName = menuName;
        return this;
    }

    public String getDescription() {
        return description;
    }

    public SysMenuItemDTO setDescription(String description) {
        this.description = description;
        return this;
    }

    public Integer getStatus() {
        return status;
    }

    public SysMenuItemDTO setStatus(Integer status) {
        this.status = status;
        return this;
    }
}
