package com.hz.admin.model.pojo.dto.menu;

import com.dzzh.hz.hzsf.common.pojo.CommonPojo;

import java.util.List;

/**
 * @Classname SysMenuDTO
 * @Description TODO
 * @Date 2020-07-27 23:32
 * @Created by hzong
 */
public class SysMenuDTO extends CommonPojo {


    /**
     * Database Column Remarks:
     *   菜单名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_menu.menu_name
     *
     * @mbg.generated
     */
    private String menuName;


    /**
     * 地址
     */
    private String url;
    /**
     * 图标
     */
    private String icon;

    /**
     * 子菜单
     */
    private List<SysMenuDTO> items;


    public String getIcon() {
        return icon;
    }

    public SysMenuDTO setIcon(String icon) {
        this.icon = icon;
        return this;
    }

    public String getMenuName() {
        return menuName;
    }

    public SysMenuDTO setMenuName(String menuName) {
        this.menuName = menuName;
        return this;
    }

    public List<SysMenuDTO> getItems() {
        return items;
    }

    public SysMenuDTO setItems(List<SysMenuDTO> items) {
        this.items = items;
        return this;
    }

    public String getUrl() {
        return url;
    }

    public SysMenuDTO setUrl(String url) {
        this.url = url;
        return this;
    }
}
