package com.hz.admin.model.pojo.dto.account;

import com.dzzh.hz.hzsf.common.pojo.CommonPojo;

/**
 * @Classname AccountDTO
 * @Description TODO
 * @Date 2020-04-30 18:01
 * @Created by hzong
 */
public class AccountDTO extends CommonPojo {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_account.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_account.cust_no
     *
     * @mbg.generated
     */
    private Long custNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_account.pwd
     *
     * @mbg.generated
     */
    private String pwd;

    /**
     * Database Column Remarks:
     *   1 锁定 2 不锁定
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hz_account.status
     *
     * @mbg.generated
     */
    private Integer status;

    public String getAccount() {
        return account;
    }

    public AccountDTO setAccount(String account) {
        this.account = account;
        return this;
    }
}
