package com.hz.admin.db.mapper;

import com.hz.admin.db.entity.TCustnoRole;
import com.hz.admin.db.entity.TCustnoRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCustnoRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_role
     *
     * @mbg.generated
     */
    long countByExample(TCustnoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_role
     *
     * @mbg.generated
     */
    int deleteByExample(TCustnoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_role
     *
     * @mbg.generated
     */
    int insert(TCustnoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_role
     *
     * @mbg.generated
     */
    int insertSelective(TCustnoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_role
     *
     * @mbg.generated
     */
    List<TCustnoRole> selectByExample(TCustnoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_role
     *
     * @mbg.generated
     */
    TCustnoRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCustnoRole record, @Param("example") TCustnoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCustnoRole record, @Param("example") TCustnoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCustnoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCustnoRole record);
}