package com.hz.admin.db.mapper;

import com.hz.admin.db.entity.TCustnoInfo;
import com.hz.admin.db.entity.TCustnoInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCustnoInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_info
     *
     * @mbg.generated
     */
    long countByExample(TCustnoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_info
     *
     * @mbg.generated
     */
    int deleteByExample(TCustnoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long custNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_info
     *
     * @mbg.generated
     */
    int insert(TCustnoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_info
     *
     * @mbg.generated
     */
    int insertSelective(TCustnoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_info
     *
     * @mbg.generated
     */
    List<TCustnoInfo> selectByExample(TCustnoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_info
     *
     * @mbg.generated
     */
    TCustnoInfo selectByPrimaryKey(Long custNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCustnoInfo record, @Param("example") TCustnoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCustnoInfo record, @Param("example") TCustnoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCustnoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_custno_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCustnoInfo record);
}