package com.hz.admin.db.mapper;

import com.hz.admin.db.entity.TMenu;
import com.hz.admin.db.entity.TMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_menu
     *
     * @mbg.generated
     */
    long countByExample(TMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_menu
     *
     * @mbg.generated
     */
    int deleteByExample(TMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_menu
     *
     * @mbg.generated
     */
    int insert(TMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_menu
     *
     * @mbg.generated
     */
    int insertSelective(TMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_menu
     *
     * @mbg.generated
     */
    List<TMenu> selectByExample(TMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_menu
     *
     * @mbg.generated
     */
    TMenu selectByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TMenu record, @Param("example") TMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TMenu record, @Param("example") TMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMenu record);
}