package com.hz.admin.db.mapper;

import com.hz.admin.db.entity.TPermission;
import com.hz.admin.db.entity.TPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_permission
     *
     * @mbg.generated
     */
    long countByExample(TPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_permission
     *
     * @mbg.generated
     */
    int deleteByExample(TPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_permission
     *
     * @mbg.generated
     */
    int insert(TPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_permission
     *
     * @mbg.generated
     */
    int insertSelective(TPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_permission
     *
     * @mbg.generated
     */
    List<TPermission> selectByExample(TPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_permission
     *
     * @mbg.generated
     */
    TPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TPermission record, @Param("example") TPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TPermission record, @Param("example") TPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hz_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TPermission record);
}
